default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password:
  host: localhost
  database: furima-39444_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-39444_test


production:
  <<: *default
  database: furima-39444_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
